FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update \
    && apt-get install -y --no-install-recommends gnupg apt-utils apache2 libapache2-mod-php \
    && echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main" > /etc/apt/sources.list.d/ondrej-php.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C \
    && apt-get update \
    && apt-get -y install curl ca-certificates unzip \
        php7.2 php7.2-cli php7.2-curl php-apcu php-apcu-bc php7.2-dev libmcrypt-dev php-pear php7.2-mongodb php7.2-curl \
        php7.2-json php7.2-mbstring php7.2-opcache php7.2-readline php7.2-xml php7.2-zip php7.2-bcmath php7.2-gd php7.2-mysql \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && composer global require hirak/prestissimo \
    && composer clear-cache \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* ~/.composer \
    && rm /var/www/html/index.html

RUN pecl install mongodb \
    && pecl install mcrypt-1.0.1 

COPY ./configsrvr/000-default.conf /etc/apache2/sites-enabled/000-default.conf
RUN a2enmod rewrite
EXPOSE 80
EXPOSE 443
WORKDIR /var/www/html/
CMD ["php", "-a"]